// Shapes returned by the backend API (backend/src/routes).

export type Role = 'WORKER' | 'MANAGER' | 'ADMIN' | 'SUPER_ADMIN'

/** Admin-panel modules a Manager can be given access to (backend/src/lib/permissions.ts). */
export type ModuleKey =
  | 'dashboard'
  | 'checks'
  | 'exceptions'
  | 'reports'
  | 'machines'
  | 'parameters'
  | 'activities'
  | 'schedules'
  | 'shifts'
  | 'departments'
  | 'workers'
  | 'assignments'
  | 'audit_logs'
  | 'settings'
  | 'calendar'

export type Access = 'none' | 'view' | 'manage'
export type Permissions = Record<ModuleKey, Access>

export interface ModuleInfo {
  key: ModuleKey
  label: string
  description: string
  viewOnly?: boolean
}

export interface ManagerAccess {
  id: string
  employeeId: string
  name: string
  designation: string | null
  isActive: boolean
  lastLoginAt: string | null
  permissions: Permissions
}
export type ParameterType = 'NUMBER' | 'TEXT' | 'DROPDOWN' | 'YES_NO' | 'PASS_FAIL'
export type MachineStatus = 'ACTIVE' | 'MAINTENANCE' | 'IDLE'
/**
 * Internal check state from the API. Only COMPLETED, MISSED and EXCEPTION are ever shown as a
 * status; PENDING / DUE / IN_PROGRESS mean "not finished yet" and are displayed as "—".
 */
export type QualityCheckStatus = 'PENDING' | 'DUE' | 'IN_PROGRESS' | 'COMPLETED' | 'MISSED' | 'EXCEPTION'
export type ExceptionStatus = 'UNDER_REVIEW' | 'ACKNOWLEDGED' | 'ACTION_TAKEN' | 'RESOLVED'
export type ValueResult = 'PASS' | 'FAIL' | 'NA'

/** Overall result of a check (backend/src/lib/result.ts). Null while the check is still open. */
export type CheckResult = 'COMPLETED' | 'MISSED' | 'EXCEPTION'

export interface CurrentUser {
  id: string
  name: string
  employeeId: string
  role: Role
  designation: string | null
  departmentName: string | null
  shiftName: string | null
  shiftStartTime: string | null
  shiftEndTime: string | null
  /** What this user may use; Admins and Super Admins have manage on everything. */
  permissions: Permissions
}

export interface Department {
  id: string
  name: string
  code: string
  isActive: boolean
}

export interface Shift {
  id: string
  name: string
  code: string
  startTime: string
  endTime: string
  graceMinutes: number
  isActive: boolean
}

export interface Machine {
  id: string
  name: string
  code: string
  departmentId: string | null
  departmentName: string | null
  line: string | null
  model: string | null
  status: MachineStatus
  notes: string | null
  isActive: boolean
  activityIds: string[]
}

export interface Parameter {
  id: string
  name: string
  code: string
  type: ParameterType
  unit: string | null
  minValue: number | null
  maxValue: number | null
  options: string[]
  /** Default "required" value when the parameter is added to a quality check type. */
  isRequired: boolean
  isActive: boolean
  sortOrder: number
  description: string | null
  departmentId: string | null
  departmentName: string | null
  /** Human-readable acceptance rule generated by the server. */
  rule: string | null
  activityIds: string[]
}

export interface ActivityParameter {
  parameterId: string
  sortOrder: number
  isRequired: boolean
  isEnabled: boolean
  name: string
  code: string
  type: ParameterType
  unit: string | null
  parameterActive: boolean
}

/** A quality check type (process): its parameters, evidence rules and machines. */
export interface Activity {
  id: string
  name: string
  code: string
  departmentId: string | null
  departmentName: string | null
  description: string | null
  requirePhoto: boolean
  requireVideo: boolean
  requireJobNo: boolean
  isActive: boolean
  parameters: ActivityParameter[]
  machineIds: string[]
}

export interface Schedule {
  id: string
  machineId: string
  activityId: string
  shiftId: string
  workerId: string | null
  intervalMinutes: number
  startTime: string | null
  endTime: string | null
  isActive: boolean
  machineName: string
  activityName: string
  shiftName: string
  shiftStartTime: string
  shiftEndTime: string
  workerName: string | null
  workerEmployeeId: string | null
  /** Workers who get this schedule's checks. Empty: no worker on this machine and shift, so no checks. */
  checkWorkers: { id: string; name: string; employeeId: string }[]
}

/** A schedule that creates no checks because its machine has no worker on that shift. */
export interface WorkerGap {
  scheduleId: string
  machineName: string
  shiftName: string
  activityName: string
}

export interface User {
  id: string
  employeeId: string
  name: string
  role: Role
  designation: string | null
  departmentId: string | null
  departmentName: string | null
  shiftId: string | null
  shiftName: string | null
  phone: string | null
  isActive: boolean
  /** May sign in to the worker mobile app. */
  appAccess: boolean
  lastLoginAt: string | null
  createdAt: string
  /** Machines the worker may check. */
  machineIds: string[]
}

export interface MediaFile {
  id: string
  kind: 'PHOTO' | 'VIDEO'
  /** Relative URL, use mediaUrl() from lib/api. */
  url: string
  mimeType: string
  sizeBytes: number
  sha256: string
  durationSeconds: number | null
  capturedAt: string | null
  createdAt: string
}

export interface CheckValue {
  parameterId: string | null
  parameterName: string
  parameterType: ParameterType
  unit: string | null
  rule: string | null
  value: string | null
  result: ValueResult
}

export interface CheckException {
  id: string
  reason: string
  remark: string | null
  status: ExceptionStatus
  reviewedByName: string | null
  resolutionNotes: string | null
  createdAt: string
  media: MediaFile[]
}

export interface QualityCheck {
  id: string
  code: string
  scheduleId: string | null
  machineId: string
  machineName: string
  machineCode: string
  departmentId: string | null
  departmentName: string | null
  activityId: string
  activityName: string
  workerId: string | null
  workerName: string | null
  workerEmployeeId: string | null
  shiftId: string | null
  shiftName: string | null
  scheduledAt: string
  windowEndsAt: string
  status: QualityCheckStatus
  result: CheckResult | null
  jobNo: string | null
  submittedAt: string | null
  submittedById: string | null
  submittedByName: string | null
  submittedByEmployeeId: string | null
  deviceInfo: string | null
  values: CheckValue[]
  media: MediaFile[]
  exception: CheckException | null
}

export interface ExceptionRecord extends CheckException {
  checkId: string
  checkCode: string
  machineId: string
  machineName: string
  departmentName: string | null
  activityName: string
  workerName: string | null
  workerEmployeeId: string | null
  scheduledAt: string
}

export interface AuditLog {
  id: string
  userId: string | null
  userName: string | null
  role: string | null
  action: string
  entity: string
  entityId: string | null
  oldValue: unknown
  newValue: unknown
  ipAddress: string | null
  createdAt: string
}

export interface KPISummary {
  scheduled: number
  /** Checks whose result is Completed. */
  completed: number
  missed: number
  exceptions: number
  /** Checks not finished yet (no status). */
  open: number
  completionRate: number
}

export interface MachineSummary {
  machineId: string
  machineName: string
  total: number
  completed: number
  missed: number
  exceptions: number
  open: number
}

export interface DashboardData {
  from: string
  to: string
  kpi: KPISummary
  byMachine: MachineSummary[]
  recent: QualityCheck[]
  /** Set when the plant is closed on the chosen day (Plant Calendar). */
  closure: { id: string; date: string; type: ClosureType; label: string; reason: string | null } | null
  workerGaps: WorkerGap[]
}

/** Plant Calendar: how a closed day is labelled. */
export type ClosureType = 'CLOSED' | 'HOLIDAY' | 'SHUTDOWN'

/** A date the plant is closed. No checks, alerts or Missed checks on that date. */
export interface PlantClosure {
  id: string
  /** Local date, YYYY-MM-DD. */
  date: string
  type: ClosureType
  reason: string | null
  updatedAt: string
}

export type Settings = Record<string, unknown>
