// Shapes returned by the backend API (backend/src/routes).

export type Role = 'WORKER' | 'MANAGER' | 'ADMIN' | 'SUPER_ADMIN'

/** Admin-panel modules a Manager can be given access to (backend/src/lib/permissions.ts). */
export type ModuleKey =
  | 'dashboard'
  | 'checks'
  | 'exceptions'
  | 'reports'
  | 'machines'
  | 'parameters'
  | 'activities'
  | 'schedules'
  | 'shifts'
  | 'departments'
  | 'workers'
  | 'assignments'
  | 'audit_logs'
  | 'settings'
  | 'calendar'

export type Access = 'none' | 'view' | 'manage'
export type Permissions = Record<ModuleKey, Access>

export interface ModuleInfo {
  key: ModuleKey
  label: string
  description: string
  viewOnly?: boolean
}

export interface ManagerAccess {
  id: string
  employeeId: string
  name: string
  designation: string | null
  isActive: boolean
  lastLoginAt: string | null
  permissions: Permissions
}
export type ParameterType = 'NUMBER' | 'TEXT' | 'DROPDOWN' | 'YES_NO' | 'PASS_FAIL'
export type MachineStatus = 'ACTIVE' | 'MAINTENANCE' | 'IDLE'
/**
 * Internal check state from the API. Only COMPLETED, MISSED and EXCEPTION are ever shown as a
 * status; PENDING / DUE / IN_PROGRESS mean "not finished yet" and are displayed as "—".
 */
export type QualityCheckStatus = 'PENDING' | 'DUE' | 'IN_PROGRESS' | 'COMPLETED' | 'MISSED' | 'EXCEPTION'
export type ExceptionStatus = 'UNDER_REVIEW' | 'ACKNOWLEDGED' | 'ACTION_TAKEN' | 'RESOLVED'
export type ValueResult = 'PASS' | 'FAIL' | 'NA'

/** When a parameter has to be filled in: always, or only while a production job runs on the machine. */
export type AppliesWhen = 'ALWAYS' | 'JOB_RUNNING'

/** Who started the check: the scheduler (a notification) or the worker (manual submission). */
export type SubmissionType = 'NOTIFICATION' | 'MANUAL'

/** How a schedule creates checks: on a rolling interval, or only while a job runs. */
export type ScheduleMode = 'INTERVAL' | 'JOB'

/** A check type on a machine has no interval schedule, so it can only be started by hand. */
export type MonitoringMode = ScheduleMode | 'MANUAL'

/** Overall result of a check (backend/src/lib/result.ts). Null while the check is still open. */
export type CheckResult = 'COMPLETED' | 'MISSED' | 'EXCEPTION'

export interface CurrentUser {
  id: string
  name: string
  employeeId: string
  role: Role
  designation: string | null
  departmentName: string | null
  shiftName: string | null
  shiftStartTime: string | null
  shiftEndTime: string | null
  /** What this user may use; Admins and Super Admins have manage on everything. */
  permissions: Permissions
}

export interface Department {
  id: string
  name: string
  code: string
  isActive: boolean
}

export interface Shift {
  id: string
  name: string
  code: string
  startTime: string
  endTime: string
  graceMinutes: number
  isActive: boolean
}

export interface Machine {
  id: string
  name: string
  code: string
  departmentId: string | null
  departmentName: string | null
  line: string | null
  model: string | null
  status: MachineStatus
  notes: string | null
  isActive: boolean
  activityIds: string[]
}

export interface Parameter {
  id: string
  name: string
  code: string
  type: ParameterType
  unit: string | null
  minValue: number | null
  maxValue: number | null
  options: string[]
  /** Default "required" value when the parameter is added to a quality check type. */
  isRequired: boolean
  isActive: boolean
  sortOrder: number
  description: string | null
  departmentId: string | null
  departmentName: string | null
  /** Human-readable acceptance rule generated by the server. */
  rule: string | null
  activityIds: string[]
}

export interface ActivityParameter {
  parameterId: string
  sortOrder: number
  isRequired: boolean
  isEnabled: boolean
  name: string
  code: string
  type: ParameterType
  unit: string | null
  parameterActive: boolean
  /** Evidence the worker must capture for this parameter, on top of its reading. */
  requirePhoto: boolean
  requireVideo: boolean
  /** The worker may mark this parameter "Not applicable" with one of the monitoring reasons. */
  allowNa: boolean
  /** JOB_RUNNING parameters are automatically Not applicable when no job runs on the machine. */
  appliesWhen: AppliesWhen
}

/** A quality check type (process): its parameters, evidence rules and machines. */
export interface Activity {
  id: string
  name: string
  code: string
  departmentId: string | null
  departmentName: string | null
  description: string | null
  requirePhoto: boolean
  requireVideo: boolean
  requireJobNo: boolean
  /** The worker may start this check from the machine screen without waiting for a notification. */
  allowManual: boolean
  isActive: boolean
  parameters: ActivityParameter[]
  machineIds: string[]
}

export interface Schedule {
  id: string
  machineId: string
  activityId: string
  shiftId: string
  workerId: string | null
  intervalMinutes: number
  startTime: string | null
  endTime: string | null
  /** INTERVAL: checks all through the shift. JOB: only while a job runs on the machine. */
  mode: ScheduleMode
  isActive: boolean
  machineName: string
  activityName: string
  shiftName: string
  shiftStartTime: string
  shiftEndTime: string
  workerName: string | null
  workerEmployeeId: string | null
  /** Workers who get this schedule's checks. Empty: no worker on this machine and shift, so no checks. */
  checkWorkers: { id: string; name: string; employeeId: string }[]
  /** Rolling timer (only sent by endpoints that read schedule_timers). */
  nextDueAt?: string | null
  lastSubmittedAt?: string | null
}

/** A schedule that creates no checks because its machine has no worker on that shift. */
export interface WorkerGap {
  scheduleId: string
  machineName: string
  shiftName: string
  activityName: string
}

export interface User {
  id: string
  employeeId: string
  name: string
  role: Role
  designation: string | null
  departmentId: string | null
  departmentName: string | null
  shiftId: string | null
  shiftName: string | null
  phone: string | null
  isActive: boolean
  /** May sign in to the worker mobile app. */
  appAccess: boolean
  lastLoginAt: string | null
  createdAt: string
  /** Machines the worker may check. */
  machineIds: string[]
}

export interface MediaFile {
  id: string
  kind: 'PHOTO' | 'VIDEO'
  /** The parameter this evidence belongs to; null for overall (or legacy) check evidence. */
  parameterId: string | null
  /** Relative URL, use mediaUrl() from lib/api. */
  url: string
  mimeType: string
  sizeBytes: number
  sha256: string
  durationSeconds: number | null
  capturedAt: string | null
  createdAt: string
}

export interface CheckValue {
  parameterId: string | null
  parameterName: string
  parameterType: ParameterType
  unit: string | null
  rule: string | null
  value: string | null
  result: ValueResult
  /** Marked "Not applicable" by the worker, or automatically because no job was running. */
  notApplicable: boolean
  naReason: string | null
  naRemark: string | null
  appliesWhen: AppliesWhen | null
}

export interface CheckException {
  id: string
  reason: string
  remark: string | null
  status: ExceptionStatus
  reviewedByName: string | null
  resolutionNotes: string | null
  createdAt: string
  media: MediaFile[]
}

export interface QualityCheck {
  id: string
  code: string
  scheduleId: string | null
  machineId: string
  machineName: string
  machineCode: string
  departmentId: string | null
  departmentName: string | null
  activityId: string
  activityName: string
  workerId: string | null
  workerName: string | null
  workerEmployeeId: string | null
  shiftId: string | null
  shiftName: string | null
  scheduledAt: string
  windowEndsAt: string
  status: QualityCheckStatus
  result: CheckResult | null
  itemCode?: string | null
  jobNo: string | null
  /** MANUAL when the worker started the check, NOTIFICATION when the scheduler did. */
  submissionType: SubmissionType
  jobId: string | null
  /** When the next check of this schedule became due, worked out at submission. */
  nextDueAt: string | null
  /** The production job this check belongs to (only sent by the single-check endpoint). */
  job?: { id: string; itemCode?: string | null; jobNo: string; startedAt: string; endedAt: string | null } | null
  submittedAt: string | null
  submittedById: string | null
  submittedByName: string | null
  submittedByEmployeeId: string | null
  deviceInfo: string | null
  values: CheckValue[]
  media: MediaFile[]
  exception: CheckException | null
}

export interface ExceptionRecord extends CheckException {
  checkId: string
  checkCode: string
  machineId: string
  machineName: string
  departmentName: string | null
  activityName: string
  workerName: string | null
  workerEmployeeId: string | null
  scheduledAt: string
}

export interface AuditLog {
  id: string
  userId: string | null
  userName: string | null
  role: string | null
  action: string
  entity: string
  entityId: string | null
  oldValue: unknown
  newValue: unknown
  ipAddress: string | null
  createdAt: string
}

export interface KPISummary {
  scheduled: number
  /** Checks whose result is Completed. */
  completed: number
  missed: number
  exceptions: number
  /** Checks not finished yet (no status). */
  open: number
  completionRate: number
}

export interface MachineSummary {
  machineId: string
  machineName: string
  total: number
  completed: number
  missed: number
  exceptions: number
  open: number
}

export interface DashboardData {
  from: string
  to: string
  kpi: KPISummary
  byMachine: MachineSummary[]
  recent: QualityCheck[]
  /** Set when the plant is closed on the chosen day (Plant Calendar). */
  closure: { id: string | null; date: string; type: ClosureType; label: string; reason: string | null; weeklyOff?: boolean } | null
  workerGaps: WorkerGap[]
}

/** Plant Calendar entry type. WORKING is an adjustment working day: the plant runs normally. */
export type ClosureType = 'CLOSED' | 'HOLIDAY' | 'SHUTDOWN' | 'WORKING'

/** Whether the plant is open on a date, and why (GET /api/plant-closures/days). */
export interface DayState {
  date: string
  closed: boolean
  source: 'ENTRY' | 'WEEKLY' | 'OPEN'
  /** The weekly closure falls on this date (an entry may override it). */
  weeklyClosed: boolean
  entry: { id: string; type: ClosureType; reason: string | null; calendarYearId: string | null } | null
  label: string | null
}

/** A recurring weekly closure from 2027 onwards (inclusive dates; no end date = open-ended). */
export interface WeeklyRule {
  id: string
  weekday: number
  effectiveFrom: string
  effectiveTo: string | null
  note: string | null
  updatedAt: string
}

export type CalendarYearStatus = 'DRAFT' | 'APPROVED'

export interface CalendarYear {
  id: string
  year: number
  status: CalendarYearStatus
  pendingChanges: boolean
  sourceFileName: string | null
  sourceMimeType: string | null
  extractionMethod: 'EXCEL' | 'PDF_TEXT' | 'OCR' | 'MANUAL' | null
  extractionNote: string | null
  hasDocument: boolean
  approvedAt: string | null
  updatedAt: string
}

export interface CalendarYearSummary extends CalendarYear {
  holidays: number
  workingDays: number
  openIssues: number
}

export interface CalendarYearItem {
  id: string
  type: ClosureType
  date: string | null
  name: string | null
  forHolidayDate: string | null
  printedWeekday: string | null
  sourceText: string | null
  sourceRow: number | null
  uncertainFields: string[]
  confirmed: boolean
  position: number
}

export interface CalendarIssue {
  code: string
  severity: 'BLOCKING' | 'CHECK' | 'INFO'
  message: string
  itemId: string | null
}

export interface CalendarYearDetail {
  year: CalendarYear
  items: CalendarYearItem[]
  issues: CalendarIssue[]
  canApprove: boolean
  publishedCount: number
}

/** A date the plant is closed. No checks, alerts or Missed checks on that date. */
export interface PlantClosure {
  id: string
  /** Local date, YYYY-MM-DD. */
  date: string
  type: ClosureType
  reason: string | null
  updatedAt: string
}

export type Settings = Record<string, unknown>

// ---------------------------------------------------------------- advanced monitoring

/** A reason a worker may pick when marking a parameter "Not applicable" (GET /api/monitoring-reasons). */
export interface MonitoringReason {
  id: string
  label: string
  /** The worker must also write what happened (e.g. "Other"). */
  requiresRemark: boolean
  isActive: boolean
  sortOrder: number
}

/** A production job on a machine, started and ended by the worker (GET /api/jobs). */
export interface Job {
  id: string
  machineId: string
  machineName: string
  machineCode: string
  itemCode?: string | null
  jobNo: string
  startedAt: string
  startedById: string | null
  startedByName: string | null
  endedAt: string | null
  endedById: string | null
  endedByName: string | null
  /** Checks submitted during the job. */
  checkCount: number
  durationMinutes: number
}

/** The job running on a machine, as sent inside the monitoring overview. */
export interface RunningJob {
  id: string
  machineId: string
  itemCode?: string | null
  jobNo: string
  startedAt: string
  startedById: string | null
  startedByName: string | null
  endedAt: string | null
}

/** One shift's schedule of a check type, with its rolling timer. */
export interface OverviewSchedule {
  id: string
  shiftId: string
  shiftName: string
  intervalMinutes: number
  mode: ScheduleMode
  startTime: string | null
  endTime: string | null
  isActive: boolean
  workerId: string | null
  workerName: string | null
  nextDueAt: string | null
  lastSubmittedAt: string | null
}

/** One parameter of a check type, with the evidence the worker must capture for it. */
export interface OverviewParameter {
  parameterId: string
  name: string
  code: string
  type: ParameterType
  unit: string | null
  rule: string | null
  isRequired: boolean
  isEnabled: boolean
  requirePhoto: boolean
  requireVideo: boolean
  allowNa: boolean
  appliesWhen: AppliesWhen
  sortOrder: number
}

/** A check type as it runs on one machine. */
export interface OverviewCheckType {
  activityId: string
  activityName: string
  activityCode: string
  isActive: boolean
  allowManual: boolean
  requireJobNo: boolean
  requirePhoto: boolean
  requireVideo: boolean
  /** JOB when any schedule on this machine is job-based, INTERVAL with interval schedules, else MANUAL. */
  mode: MonitoringMode
  schedules: OverviewSchedule[]
  parameters: OverviewParameter[]
}

export interface OverviewMachine {
  id: string
  name: string
  code: string
  status: MachineStatus
  departmentName: string | null
  runningJob: RunningJob | null
  checkTypes: OverviewCheckType[]
}

/** Machine-centric view of the monitoring configuration (GET /api/monitoring-overview). */
export interface MonitoringOverview {
  machines: OverviewMachine[]
}
